services:
  tgbot:
    build: .
    restart: always
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: antispambot
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
